version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: crm-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-crm_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-crm_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-crm:
    build:
      context: ./services/core-crm
      dockerfile: Dockerfile
    container_name: core-crm
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432/${POSTGRES_DB:-crm_db}
      - PORT=3001
      - NODE_ENV=development
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  ai-service:
    build:
      context: ./services/ai-service
      dockerfile: Dockerfile
    container_name: ai-service
    environment:
      - PORT=8000
    ports:
      - "8000:8000"

volumes:
  postgres_data: 