version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: crm-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-crm_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-crm_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: crm-frontend
    environment:
      - PORT=${FRONTEND_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_ORY_SDK_URL=https://auth.elphinstone.us
      - VITE_API_URL=http://core-crm:3001
      - VITE_CORE_CRM_URL=http://core-crm:3001
      - VITE_AI_SERVICE_URL=http://ai-service:8000
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - core-crm

  core-crm:
    build:
      context: ./services/core-crm
      dockerfile: Dockerfile
    container_name: core-crm
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432/${POSTGRES_DB:-crm_db}
      - PORT=${CORE_CRM_PORT:-3001}
      - NODE_ENV=${NODE_ENV:-development}
      - ORY_SDK_URL=${ORY_SDK_URL:-https://auth.elphinstone.us}
      - AI_SERVICE_URL=http://ai-service:8000
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,https://help.elphinstone.us}
    ports:
      - "${CORE_CRM_PORT:-3001}:3001"
    depends_on:
      postgres:
        condition: service_healthy

  ai-service:
    build:
      context: ./services/ai-service
      dockerfile: Dockerfile
    container_name: ai-service
    environment:
      - PORT=${AI_SERVICE_PORT:-8000}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432/${POSTGRES_DB:-crm_db}
      - NODE_ENV=${NODE_ENV:-development}
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,https://help.elphinstone.us}
    ports:
      - "${AI_SERVICE_PORT:-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

volumes:
  postgres_data: 